// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Add book to cart', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('Add book to cart', async function () {
    await driver.get("http://bookstore11.azurewebsites.net/")
    await driver.manage().window().setRect({ width: 784, height: 824 })

    // Wait for the button to be clickable and then click it
    await driver.wait(until.elementIsClickable(driver.findElement(By.css(".book:nth-child(1) > button"))));
    await driver.findElement(By.css(".book:nth-child(1) > button")).click()
  })
})
