version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test

  deploy:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build Application
          command: yarn build
      - run:
          name: Deploy to Render
          command: |
            curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "${RENDER_SERVICE_ID}", "branch": "main"}' \
            https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
