version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Set Permissions for node_modules
          command: sudo chmod 777 -R node_modules/

  test-ide-dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run IDE Tests in Dev Environment
          command: npm run test-ide

  test-grid-dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Grid Tests in Dev Environment
          command: npm run test-grid

  test-ide-stage:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run IDE Tests in Stage Environment
          command: npm run test-ide

  test-grid-stage:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Grid Tests in Stage Environment
          command: npm run test-grid

workflows:
  version: 2
  dev-workflow:
    jobs:
      - install-dependencies
      - test-ide-dev
      - test-grid-dev

  stage-workflow:
    jobs:
      - install-dependencies
      - test-ide-stage
      - test-grid-stage
