version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14-browsers # Use a Node.js image with browser support

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -yqq unzip
            wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
            sudo chown root:root /usr/local/bin/chromedriver
            sudo chmod 0755 /usr/local/bin/chromedriver
            chromedriver --version

      - run:
          name: Run Selenium Tests
          command: npm tests
          environment:
            CHROME_BIN: "/usr/bin/google-chrome"
            CHROMEDRIVER_BIN: "/usr/local/bin/chromedriver"

  deploy:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Deploy to Render
          command: |
            curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "${RENDER_SERVICE_ID}", "branch": "main"}' \
            https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
