version: 2.1

executors:
  node-executor:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      NODE_ENV: development

jobs:
  test:
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$PATH"
      - run: yarn install
      - run:
          name: Run IDE Tests
          command: yarn test-ide
      - run:
          name: Run Selenium GRID Tests
          command: yarn test-grid

  build:
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$PATH"
      - run: yarn install
      - run: yarn build

  deploy_dev:
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$PATH"
      - run: yarn install
      - run:
          name: Deploy to Development
          command: yarn deploy:dev

  deploy_stage:
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$PATH"
      - run: yarn install
      - run:
          name: Deploy to Staging
          command: yarn deploy:stage

workflows:
  version: 2
  dev_workflow:
    jobs:
      - test
      - build
      - deploy_dev:
          requires:
            - test
            - build

  stage_workflow:
    jobs:
      - test
      - build
      - deploy_stage:
          requires:
            - test
            - build
