version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  test-ide-dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run IDE Tests in Dev Environment
          command: npx mocha tests/ide/test.js --timeout 20000

  test-grid-dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Grid Tests in Dev Environment
          command: npx mocha tests/grid/runGridTests.js --timeout 20000

workflows:
  version: 2
  dev-workflow:
    jobs:
      - install-dependencies
      - test-ide-dev
      - test-grid-dev
