version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14 # Use a general Node.js 14 image

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build Project
          command: ./node_modules/.bin/yarn build --if-present

      - run:
          name: Run Tests
          command: ./node_modules/.bin/yarn test --if-present

  deploy:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build Project
          command: ./node_modules/.bin/yarn build --if-present

      - run:
          name: Deploy to Render
          command: |
            curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "${RENDER_SERVICE_ID}", "branch": "main"}' \
            https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
