version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14-buster
        environment:
          CHROME_BIN: /usr/bin/google-chrome
          NODE_ENV: test
          SELENIUM_SERVER_URL: http://localhost:4444/wd/hub

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --retry=5
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

  start-selenium:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Start Selenium Server
          command: |
            wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
            java -jar selenium-server-standalone-3.141.59.jar > /dev/null 2>&1 &
      - run:
          name: Wait for Selenium Server
          command: |
            # wait for the selenium server to be up and running
            for i in `seq 1 30`; do
              curl -s http://localhost:4444/wd/hub/status && echo "Selenium Server is up" && break
              echo "Waiting for Selenium Server..." && sleep 1
            done

  test-selenium-ide:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Selenium IDE Tests
          command: |
            mkdir -p test-results
            npm run test-ide -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-results/results.xml
      - store_test_results:
          path: test-results

  test-selenium-grid:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Create Test Results Directory
          command: mkdir -p test-results
      - run:
          name: Run Selenium Grid Tests
          command: npm run test-grid
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - install-dependencies
      - start-selenium
      - test-selenium-ide
      - test-selenium-grid
