version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

start-selenium:
  executor: node-executor
  steps:
    - checkout
    - run:
        name: Start Selenium Server
        command: |
          wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
          java -jar selenium-server-standalone-3.141.59.jar > /dev/null 2>&1 &

  test-ide-dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run IDE Tests in Dev Environment
          command: npm run test-ide

  test-grid-dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Grid Tests in Dev Environment
          command: npm run test-grid

  test-ide-stage:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run IDE Tests in Stage Environment
          command: npm run test-ide

  test-grid-stage:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Grid Tests in Stage Environment
          command: npm run test-grid

workflows:
  version: 2
  dev-workflow:
    jobs:
      - install-dependencies
      - start-selenium
      - test-ide-dev
      - test-grid-dev

  stage-workflow:
    jobs:
      - install-dependencies
      - start-selenium
      - test-ide-stage
      - test-grid-stage
