// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("Delete multiple books from cart", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Delete multiple books from cart", async function () {
    await driver.get("http://bookstore11.azurewebsites.net/");
    await driver.manage().window().setRect({ width: 784, height: 824 });
    await driver.findElement(By.id("bookList")).click();
    await driver.findElement(By.css(".book:nth-child(11) > button")).click();
    await driver.findElement(By.css(".book:nth-child(20) > button")).click();
    await driver.findElement(By.css(".book:nth-child(19) > button")).click();
    await driver.findElement(By.css("li:nth-child(1) > button")).click();
    await driver.findElement(By.css("li:nth-child(1) > button")).click();
    await driver.findElement(By.css("button:nth-child(1)")).click();
  });
});
