// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("Search book", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Search book", async function () {
    await driver.get("http://bookstore11.azurewebsites.net/");
    await driver.manage().window().setRect({ width: 784, height: 824 });
    await driver.findElement(By.id("searchInput")).click();
    await driver.findElement(By.id("searchInput")).sendKeys("book 10");
    await driver.findElement(By.css("button:nth-child(3)")).click();
  });
});
